name: run-test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '00 11 * * 1,5'
  workflow_dispatch:

jobs:
  build:
    name: Setting up environment for test run
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setting up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run tests
        run: mvn test

      - name: Report results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
